#
# AlcoTools - Alcoholicz dupe checker, zipscript, and utilities.
# Copyright (c) 2005-2006 Alcoholicz Scripting Team
#
# Module Name:
#   SQLite Makefile
#
# Author:
#   neoxed (neoxed@gmail.com) Mar 3, 2006
#
# Abstract:
#   Build configuration file for NMAKE, or a compatible tool.
#
# Instructions:
#   1. Download and unpack the latest SQLite v3.x source package.
#
#   2. Run the configuration script in a Cygwin environment.
#
#      mkdir build
#      cd build
#      ../configure --enable-threadsafe
#      make target_source
#
#   3. Copy this makefile to the "tsrc" directory.
#
#   4. Run: nmake -f makefile.sqlite all
#
#   5. Copy the following files to another location for later use.
#
#      include\sqlite3.h
#      sqlite3.dll
#      sqlite3.lib
#      sqlite3-static.lib
#

# User settings
DEBUG       = 0
STATIC_CRT  = 0

# Compiler settings
CC          = cl.exe
AR          = lib.exe
LD          = link.exe
AFLAGS      = /nologo
CFLAGS      = /nologo /D_CRT_NONSTDC_NO_DEPRECATE /D_CRT_SECURE_NO_DEPRECATE /DTHREADSAFE=1
LFLAGS      = /nologo

# -------------------------------------------------------------------------

!if "$(STATIC_CRT)" == "1"
!message *** CRT: Static
CRTLIB      = /MT
CFLAGS      = $(CFLAGS) /DSTATIC_CRT
!else
!message *** CRT: Dynamic
CRTLIB      = /MD
CFLAGS      = $(CFLAGS) /DDYNAMIC_CRT
!endif

!if "$(DEBUG)" == "1"
!message *** Debug: On
CFLAGS      = $(CFLAGS) /Zi /Od $(CRTLIB)d /DDEBUG
LFLAGS      = $(LFLAGS) /DEBUG
!else
!message *** Debug: Off
CFLAGS      = $(CFLAGS) /Ox /GF /GS- $(CRTLIB) /DNDEBUG /DSQLITE_OMIT_EXPLAIN=1
LFLAGS      = $(LFLAGS) /RELEASE /OPT:NOWIN98 /OPT:REF
!endif

# -------------------------------------------------------------------------

OBJ_FILES   = alter.obj analyze.obj attach.obj auth.obj btree.obj build.obj\
             callback.obj complete.obj date.obj delete.obj expr.obj func.obj\
             hash.obj insert.obj legacy.obj main.obj opcodes.obj os.obj os_win.obj\
             pager.obj parse.obj pragma.obj prepare.obj printf.obj random.obj\
             select.obj table.obj tokenize.obj trigger.obj update.obj utf.obj\
             util.obj vacuum.obj vdbe.obj vdbeapi.obj vdbeaux.obj vdbefifo.obj\
             vdbemem.obj where.obj

.c.obj::
    $(CC) /c $(CFLAGS) /Fo @<<
$<
<<

# -------------------------------------------------------------------------

default: all

all: dynamic static

clean:
    @DEL /F *.dll *.lib *.exp *.obj *.pdb

dynamic: sqlite3.dll

static: sqlite3-static.lib

sqlite3.dll: $(OBJ_FILES)
    $(LD) $(LFLAGS) /DLL /DEF:sqlite3.def /OUT:$@ @<<
$**
<<

sqlite3-static.lib: $(OBJ_FILES)
    $(AR) $(AFLAGS) /OUT:$@ @<<
$**
<<
